[package]
name = "axiom-dck"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "AXIOM Prototype 1.0 — dck"
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
axiom-capsule = { path = "../capsule" }
axiom-acp = { path = "../acp" }
