//! DCK — Difference Convergence Kernel v2.3 (Prototype 1.0)
//!
//! **Official taxonomy** from `Axiom-Framework/axiomFrameworkRUSTv1.6/dck`
//! Design lock: `DCK_DUAL_HASH_TAXONOMY_v2.3.md`
//!
//! License: MIT (AXIOM Framework Research License §7)
//!
//! ```text
//! PSS → PLP → Capsule → ACP → Hash A (Invariant)
//!                               │ Constraint(A)
//!                               ▼
//!                            Hash B (Semantic)
//!                               ▼
//!              DCK.DualHashEvaluation  (+ annotation metrics)
//! ```
//!
//! 実験は忠実に実際行って

use axiom_capsule::Capsule;
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;

// =============================================================================
// Official dual-hash taxonomy (v2.3)
// =============================================================================

/// Invariant / physical hash — sealed by ACP, treated as Ground Truth.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct HashA {
    pub value: String,
}

impl HashA {
    pub fn new(value: impl Into<String>) -> Self {
        Self {
            value: value.into(),
        }
    }

    pub fn same_as(&self, other: &HashA) -> bool {
        self.value == other.value
    }
}

/// Semantic / interpretation hash — may be regenerated by models or humans.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct HashB {
    pub value: String,
}

impl HashB {
    pub fn new(value: impl Into<String>) -> Self {
        Self {
            value: value.into(),
        }
    }

    pub fn same_as(&self, other: &HashB) -> bool {
        self.value == other.value
    }
}

/// Sealed pair after PLP → Capsule → ACP (A) and after interpretation (B).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DualHashSnapshot {
    pub hash_a: HashA,
    pub hash_b: HashB,
    /// Optional constraint fingerprint derived from A.
    pub constraint_id: Option<String>,
}

impl DualHashSnapshot {
    pub fn new(hash_a: HashA, hash_b: HashB) -> Self {
        Self {
            hash_a,
            hash_b,
            constraint_id: None,
        }
    }

    pub fn with_constraint(mut self, constraint_id: impl Into<String>) -> Self {
        self.constraint_id = Some(constraint_id.into());
        self
    }

    pub fn from_pair(hash_a: impl Into<String>, hash_b: impl Into<String>) -> Self {
        Self::new(HashA::new(hash_a), HashB::new(hash_b))
    }

    /// Bridge from Prototype Capsule (raw_hash = A, canonical_hash = B).
    pub fn from_capsule(c: &Capsule) -> Self {
        Self::from_pair(c.hash_a(), c.hash_b())
    }
}

/// Primary dual-hash classification (A×B matrix).
///
/// | A \ B   | same     | changed   |
/// |---------|----------|-----------|
/// | same    | None     | Semantic  |
/// | changed | State    | Compound  |
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum DualHashClass {
    /// A same, B same
    None,
    /// A same, B changed — interpretation drift
    Semantic,
    /// A changed, B same — physical / input identity change
    State,
    /// Both changed
    Compound,
}

impl DualHashClass {
    pub fn from_pair(a_same: bool, b_same: bool) -> Self {
        match (a_same, b_same) {
            (true, true) => DualHashClass::None,
            (true, false) => DualHashClass::Semantic,
            (false, true) => DualHashClass::State,
            (false, false) => DualHashClass::Compound,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            DualHashClass::None => "None",
            DualHashClass::Semantic => "Semantic",
            DualHashClass::State => "State",
            DualHashClass::Compound => "Compound",
        }
    }
}

/// Constraint validation outcome: B against Constraint(A).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum ConstraintVerdict {
    Pass,
    Fail,
    NotEvaluated,
}

impl ConstraintVerdict {
    pub fn as_str(self) -> &'static str {
        match self {
            ConstraintVerdict::Pass => "Pass",
            ConstraintVerdict::Fail => "Fail",
            ConstraintVerdict::NotEvaluated => "NotEvaluated",
        }
    }

    pub fn is_constraint_difference(self) -> bool {
        matches!(self, ConstraintVerdict::Fail)
    }
}

/// Unified difference taxonomy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum DifferenceKind {
    None,
    State,
    Semantic,
    Constraint,
    Compound,
}

impl DifferenceKind {
    pub fn as_str(self) -> &'static str {
        match self {
            DifferenceKind::None => "None",
            DifferenceKind::State => "State",
            DifferenceKind::Semantic => "Semantic",
            DifferenceKind::Constraint => "Constraint",
            DifferenceKind::Compound => "Compound",
        }
    }
}

/// Full dual-hash + constraint evaluation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DualHashEvaluation {
    pub class: DualHashClass,
    pub constraint: ConstraintVerdict,
    /// Constraint Fail takes priority over hash class.
    pub primary_kind: DifferenceKind,
    pub has_difference: bool,
    pub a_same: bool,
    pub b_same: bool,
}

impl DualHashEvaluation {
    /// `constraint_ok`: Some(true)=Pass, Some(false)=Fail, None=NotEvaluated
    pub fn evaluate(
        baseline: &DualHashSnapshot,
        current: &DualHashSnapshot,
        constraint_ok: Option<bool>,
    ) -> Self {
        let a_same = baseline.hash_a.same_as(&current.hash_a);
        let b_same = baseline.hash_b.same_as(&current.hash_b);
        let class = DualHashClass::from_pair(a_same, b_same);

        let constraint = match constraint_ok {
            Some(true) => ConstraintVerdict::Pass,
            Some(false) => ConstraintVerdict::Fail,
            None => ConstraintVerdict::NotEvaluated,
        };

        let primary_kind = if constraint.is_constraint_difference() {
            DifferenceKind::Constraint
        } else {
            match class {
                DualHashClass::None => DifferenceKind::None,
                DualHashClass::Semantic => DifferenceKind::Semantic,
                DualHashClass::State => DifferenceKind::State,
                DualHashClass::Compound => DifferenceKind::Compound,
            }
        };

        let has_difference = primary_kind != DifferenceKind::None
            || class != DualHashClass::None
            || constraint.is_constraint_difference();

        Self {
            class,
            constraint,
            primary_kind,
            has_difference,
            a_same,
            b_same,
        }
    }

    pub fn evaluate_hashes_only(baseline: &DualHashSnapshot, current: &DualHashSnapshot) -> Self {
        Self::evaluate(baseline, current, None)
    }
}

/// Pure constraint check hook — domain predicate supplied by caller.
pub fn validate_constraint<F>(
    constraint_id: Option<&str>,
    b_payload: &str,
    check: F,
) -> ConstraintVerdict
where
    F: Fn(Option<&str>, &str) -> bool,
{
    if constraint_id.is_none() && b_payload.is_empty() {
        return ConstraintVerdict::NotEvaluated;
    }
    if check(constraint_id, b_payload) {
        ConstraintVerdict::Pass
    } else {
        ConstraintVerdict::Fail
    }
}

// =============================================================================
// Annotation-set metrics (Canonical observation surface)
// =============================================================================

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DifferenceMetrics {
    pub overlap_ratio: f64,
    pub divergence: f64,
    pub added: usize,
    pub removed: usize,
    pub changed: usize,
    pub added_items: Vec<String>,
    pub removed_items: Vec<String>,
}

fn ann_keys(c: &Capsule) -> BTreeSet<String> {
    c.canonical
        .annotations
        .iter()
        .map(|a| match &a.key {
            Some(k) => format!("{}:{}:{}", a.kind, a.value, k),
            None => format!("{}:{}", a.kind, a.value),
        })
        .collect()
}

fn metrics_from_sets(a: &BTreeSet<String>, b: &BTreeSet<String>) -> DifferenceMetrics {
    let inter = a.intersection(b).count();
    let union = a.union(b).count();
    let overlap = if union == 0 {
        1.0
    } else {
        inter as f64 / union as f64
    };
    let added_items: Vec<String> = b.difference(a).cloned().collect();
    let removed_items: Vec<String> = a.difference(b).cloned().collect();
    let added = added_items.len();
    let removed = removed_items.len();
    DifferenceMetrics {
        overlap_ratio: (overlap * 10_000.0).round() / 10_000.0,
        divergence: ((1.0 - overlap) * 10_000.0).round() / 10_000.0,
        added,
        removed,
        changed: added + removed,
        added_items,
        removed_items,
    }
}

/// Annotation metrics between two Capsules.
pub fn metrics(left: &Capsule, right: &Capsule) -> DifferenceMetrics {
    metrics_from_sets(&ann_keys(left), &ann_keys(right))
}

/// Dual-hash class from two Capsules.
pub fn classify(left: &Capsule, right: &Capsule) -> DualHashClass {
    DualHashClass::from_pair(
        left.raw_hash == right.raw_hash,
        left.canonical_hash == right.canonical_hash,
    )
}

/// Full dual-hash evaluation from two Capsules.
pub fn evaluate_capsules(
    left: &Capsule,
    right: &Capsule,
    constraint_ok: Option<bool>,
) -> DualHashEvaluation {
    DualHashEvaluation::evaluate(
        &DualHashSnapshot::from_capsule(left),
        &DualHashSnapshot::from_capsule(right),
        constraint_ok,
    )
}

/// Difference Report (Prototype Phase 3 target).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DifferenceReport {
    pub dual_hash: DualHashEvaluation,
    pub metrics: DifferenceMetrics,
    pub integrity_ok: bool,
    pub summary: String,
}

/// End-to-end report for two Capsules.
pub fn report(left: &Capsule, right: &Capsule) -> DifferenceReport {
    report_with_constraint(left, right, None, true)
}

pub fn report_with_constraint(
    left: &Capsule,
    right: &Capsule,
    constraint_ok: Option<bool>,
    integrity_ok: bool,
) -> DifferenceReport {
    let dual_hash = evaluate_capsules(left, right, constraint_ok);
    let metrics = metrics(left, right);
    let summary = format!(
        "{} vs {} | class={} primary={} constraint={} divergence={:.4} added={} removed={} integrity={}",
        left.id,
        right.id,
        dual_hash.class.as_str(),
        dual_hash.primary_kind.as_str(),
        dual_hash.constraint.as_str(),
        metrics.divergence,
        metrics.added,
        metrics.removed,
        integrity_ok
    );
    DifferenceReport {
        dual_hash,
        metrics,
        integrity_ok,
        summary,
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use axiom_plp::{Annotation, CanonicalState, PAYLOAD_VERSION};
    use std::collections::BTreeMap;

    fn capsule(
        id: &str,
        raw: &str,
        raw_h: &str,
        can_h: &str,
        anns: Vec<(String, String)>,
    ) -> Capsule {
        let annotations: Vec<Annotation> = anns
            .into_iter()
            .map(|(k, v)| Annotation {
                kind: k,
                value: v,
                key: None,
            })
            .collect();
        let mut meta = BTreeMap::new();
        meta.insert(
            "annotation_status".into(),
            "canonical_projection_candidate".into(),
        );
        Capsule {
            id: id.into(),
            raw_text: raw.into(),
            raw_hash: raw_h.into(),
            canonical_hash: can_h.into(),
            canonical: CanonicalState {
                version: PAYLOAD_VERSION.into(),
                language: "en".into(),
                tokens: vec![],
                annotations,
                meta,
            },
        }
    }

    #[test]
    fn matrix_none() {
        let e = DualHashEvaluation::evaluate_hashes_only(
            &DualHashSnapshot::from_pair("A", "B"),
            &DualHashSnapshot::from_pair("A", "B"),
        );
        assert_eq!(e.class, DualHashClass::None);
        assert_eq!(e.primary_kind, DifferenceKind::None);
    }

    #[test]
    fn matrix_semantic() {
        let e = DualHashEvaluation::evaluate_hashes_only(
            &DualHashSnapshot::from_pair("A", "B1"),
            &DualHashSnapshot::from_pair("A", "B2"),
        );
        assert_eq!(e.class, DualHashClass::Semantic);
        assert_eq!(e.primary_kind, DifferenceKind::Semantic);
    }

    #[test]
    fn matrix_state() {
        let e = DualHashEvaluation::evaluate_hashes_only(
            &DualHashSnapshot::from_pair("A1", "B"),
            &DualHashSnapshot::from_pair("A2", "B"),
        );
        assert_eq!(e.class, DualHashClass::State);
    }

    #[test]
    fn matrix_compound() {
        let e = DualHashEvaluation::evaluate_hashes_only(
            &DualHashSnapshot::from_pair("A1", "B1"),
            &DualHashSnapshot::from_pair("A2", "B2"),
        );
        assert_eq!(e.class, DualHashClass::Compound);
    }

    #[test]
    fn constraint_priority() {
        let base = DualHashSnapshot::new(HashA::new("capsule_abc"), HashB::new("out_v1"));
        let cur = DualHashSnapshot::new(HashA::new("capsule_abc"), HashB::new("out_v2"));
        let ev = DualHashEvaluation::evaluate(&base, &cur, Some(false));
        assert_eq!(ev.class, DualHashClass::Semantic);
        assert_eq!(ev.primary_kind, DifferenceKind::Constraint);
    }

    #[test]
    fn capsule_report_semantic() {
        let l = capsule(
            "L",
            "enable bot",
            "raw_same",
            "can_v1",
            vec![("ACTION".into(), "enable".into())],
        );
        let r = capsule(
            "R",
            "enable bot",
            "raw_same",
            "can_v2",
            vec![("ACTION".into(), "publish".into())],
        );
        let rep = report(&l, &r);
        assert_eq!(rep.dual_hash.class, DualHashClass::Semantic);
        assert!(rep.metrics.divergence > 0.0);
        assert!(rep.summary.contains("Semantic"));
    }
}
